// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk4GZLmgojWN7hL34YooSUpVbLdfR1tSY',
    appId: '1:569687570636:android:3221669b74a2a49a6f2a69',
    messagingSenderId: '569687570636',
    projectId: 'shopping-app-with-get-x-a0ade',
    storageBucket: 'shopping-app-with-get-x-a0ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9cZC-yXyWjXszrwjSZZzLyK9qICm7Z0Q',
    appId: '1:569687570636:ios:c7f30afa218395aa6f2a69',
    messagingSenderId: '569687570636',
    projectId: 'shopping-app-with-get-x-a0ade',
    storageBucket: 'shopping-app-with-get-x-a0ade.firebasestorage.app',
    iosClientId: '569687570636-ekvu0vkbn6snlfcocji7e3kni0d6ibao.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingAppWithGetx',
  );

}